mqtt:
  host: # Add IP address of mqtt host
  port: 1883 # change if needed
  user: # Add mqtt username
  password: # Add mqtt password (in ' )
  qos: 1
  base_topic: eheim_digital
  home_assistant: True

general:
  host: # Add IP address of master device
  devices:
    - type: filter
      mac: # enter mac address
    - type: heater
      mac: # enter mac address
    - type: led_control
      mac: # enter mac address
  request_frequency: 10 # value in s for requesting new data from devices
  log_level: info
