"""Constants for eheim_digital."""
from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

NAME = "EHEIM Digital"
DOMAIN = "eheim_digital"
VERSION = "0.0.1"

# device version
VERSION_UNDEFINED = 0
VERSION_HC = 1
VERSION_HC_PLUS = 2
VERSION_EHEIM_LIGHT = 3
VERSION_EHEIM_EXT_FILTER = 4
VERSION_EHEIM_EXT_HEATER = 5
VERSION_EHEIM_FEEDER = 6
VERSION_EHEIM_CHILLER = 7
VERSION_EHEIM_LIGHT_AQUAKIDS = 8
VERSION_EHEIM_PH_CONTROL = 9
VERSION_EHEIM_STREAM_CONTROL = 10
VERSION_EHEIM_REEFLEX = 11
VERSION_EHEIM_80_FILTER_WITH_HEAT = 12
VERSION_EHEIM_80_FILTER_WITHOUT_HEAT = 13
VERSION_EHEIM_DOSING_PUMP = 14
VERSION_EHEIM_LED_CTRL_PLUS_E = 15
VERSION_EHEIM_RGB_CTRL_PLUS_E = 16
VERSION_EHEIM_CLASSIC_LED_CTRL_PLUS_E = 17
VERSION_EHEIM_CLASSIC_VARIO = 18

# filter pump modes
PM_NORMAL = 1
PM_AUTOOFF = 2
PM_NACHT = 4
PM_PULS = 8
PM_REGLOFF = 16
PM_PROGMODE = 32
PM_EXTERNAL = 16
PM_HIDE_DSP = 128
PM_ROTOR_ERR = 512
PM_AIR_ERR = 768
PM_TEMP_ERR = 1280
PM_CAL_RECALC = 8192
PM_CALIBRATION = 16384
PM_RESET = 32768
